###

# curl -X POST http://localhost:3000/users
#-H "Content-Type: application/json"
#-d '{
#  "pseudonym": "john_doe",
#  "password": "SecurePa$$w0rd",
#  "name": "John Doe",
#  "address": {
#    "street": "123 Main St",
#    "city": "Anytown",
#    "zipCode": "12345",
#    "country": "Country"
#  },
#  "comment": "This is a test user.",
#  "userType": "user"
#}'
POST http://localhost:3000/users
Content-Type: application/json

{
  "pseudonym": "mzahaf",
  "password": "ACz9X8H0pa5Kk66",
  "name": "Mohammed ZAHAF",
  "address": {
    "street": "1, rue de la paix",
    "city": "Paris",
    "zipCode": "75001",
    "country": "France"
  },
  "comment": ":: Ceci est mon commentaire ::",
  "role": "admin"
}

